### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by ruskichris** [marlkiller/Orcus-1.9.1-crack#1]
How would i go about removing the auth from the setup itself? im just a bit confused :D

**Comment by marlkiller** [comment]
> How would i go about removing the auth from the setup itself? im just a bit confused :D

Switch to the `crack` branch

**Comment by ruskichris** [comment]
i already made my own fix this, now another issue, you cant use plugins with this :D, is there any way to fix this? i get this issue
`2021-05-04 00:52:56.4916|ERROR|Orcus.Administration.Core.Plugins.PluginManager|Failed to load plugin "Screamer.orcplg": System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Orcus.Administration.Core.Plugins.PluginManager.LoadPlugin(FileInfo file) in C:\Users\Admin\Desktop\orcus source\Orcus.Administration.Core\Plugins\PluginManager.cs:line 145
   at Orcus.Administration.Core.Plugins.PluginManager.Initialize() in C:\Users\Admin\Desktop\orcus source\Orcus.Administration.Core\Plugins\PluginManager.cs:line 58System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`
Only one of my plugins worked, it was a camera light disable plugin, all my other 14 plugins didnt work. Would you be able to fix this or even give me a solution to fix this?

**Comment by marlkiller** [comment]
The leakage source lacks `signApp.bat` this file
After packaging program no signature.
I think so !

> i already made my own fix this, now another issue, you cant use plugins with this :D, is there any way to fix this? i get this issue
> `2021-05-04 00:52:56.4916|ERROR|Orcus.Administration.Core.Plugins.PluginManager|Failed to load plugin "Screamer.orcplg": System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) at System.Reflection.RuntimeModule.GetTypes() at System.Reflection.Assembly.GetTypes() at Orcus.Administration.Core.Plugins.PluginManager.LoadPlugin(FileInfo file) in C:\Users\Admin\Desktop\orcus source\Orcus.Administration.Core\Plugins\PluginManager.cs:line 145 at Orcus.Administration.Core.Plugins.PluginManager.Initialize() in C:\Users\Admin\Desktop\orcus source\Orcus.Administration.Core\Plugins\PluginManager.cs:line 58System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`
> Only one of my plugins worked, it was a camera light disable plugin, all my other 14 plugins didnt work. Would you be able to fix this or even give me a solution to fix this?

**Comment by ruskichris** [comment]
nope i made the signapp.bat and it didnt fix it

**Comment by marlkiller** [comment]
> signapp.bat

**Comment by marlkiller** [comment]
> nope i made the signapp.bat and it didnt fix it

Do you have the signapp.bat file? Can you send me a copy

**Comment by ruskichris** [comment]
Its empty, like litterly there is nothing in there. I just made the file to see if it would work but it didnt work.
